### ISSUE TITLE
Use the json API on pypi to get descriptions for the pypi packages

### ISSUE THREAD

**Issue by ericdill** [ericdill/conda-skeletor#9]
cc @tonyfast

http://stackoverflow.com/questions/21419009/json-api-for-pypi-how-to-list-packages

It would be great to include the description of the package in the package requirements in the meta.yaml of the conda-recipe

e.g., 
- https://pypi.python.org/pypi/scikit-image/json
- https://pypi.python.org/pypi/scikit-xray/json

**Comment by tonyfast** [comment]
I'll try to see if I can add something this, but just so we have it.  Here is the [Conda package metadata](http://repo.continuum.io/pkgs/metadata.json)

**Comment by ericdill** [comment]
Thanks for the continuum package info link!  With 8157025 in #10 , the info from continuum has been incorporated into the meta.yaml generation.  It is configurable which order to search in (i.e., pypi then continuum or continuum then pypi). 

The meta.yaml now looks like this:

```
requirements:
  build:
    - python
    - numpy # (conda) array processing for numbers, strings, records, and objects.
    - setuptools # (conda) Easily download, build, install, upgrade, and uninstall Python packages
    - six # (conda) Python 2 and 3 compatibility utilities
  run:
    - python
    - lmfit # (pypi) Least-Squares Minimization with Bounds and Constraints
    - netcdf4 # (conda) python/numpy interface to netCDF library
    - numpy # (conda) array processing for numbers, strings, records, and objects.
    - scipy # (conda) Scientific Library for Python
    - six # (conda) Python 2 and 3 compatibility utilities
    - xraylib # No package info found for xraylib at any of these locations: ['conda', 'pypi']

test:
  requires:
    - nose # (conda) nose extends unittest to make testing easier
    - scikit-image # (conda) Image processing routines for SciPy
```

**Comment by tonyfast** [comment]
I think if no information is found then the comment should be left blank.

Can conda build from a github repo like pypi can?   This syntax ...
`- git+https://github.com/ericdill/conda-skeletor.git`

**Comment by tonyfast** [comment]
Also, it might be preferable to put the package distribution at the end of the string.

```
requirements:
  build:
    - python
    - numpy # array processing for numbers, strings, records, and objects. (conda) 
    - setuptools # Easily download, build, install, upgrade, and uninstall Python packages (conda) 
    - six # Python 2 and 3 compatibility utilities (conda) 
  run:
    - python
    - lmfit # Least-Squares Minimization with Bounds and Constraints (pypi) 
    - netcdf4 # python/numpy interface to netCDF library (conda)
    - numpy # array processing for numbers, strings, records, and objects. (conda) 
    - scipy # Scientific Library for Python (conda) 
    - six # Python 2 and 3 compatibility utilities (conda) 
    - xraylib 

test:
  requires:
    - nose # nose extends unittest to make testing easier (conda)
    - scikit-image # Image processing routines for SciPy (conda) 
```
